import type { Metadata } from "next";
import "./globals.css";
// Import the font utility

import localFont from "next/font/local";
import DebugConsoleProvider from "@/components/ui/debug-console";

// Load your custom variable font
const aspekta = localFont({
  src: "../../public/AspektaVariable-Regular.otf", // path to the font file
  display: "swap", // optional, can be 'auto', 'block', 'swap', 'fallback', or 'optional'
  weight: "100 900", // specify the range of weights supported by the variable font
  style: "normal", // specify the font style
  variable: "--font-aspekta",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${aspekta.className}  antialiased`}>
        <DebugConsoleProvider>{children}</DebugConsoleProvider>
      </body>
    </html>
  );
}
